export const CE_ENCRYPTIONER_DEFAULT = {
  MAX_SALT: 16,
  DEFAULT_SALT: 8,
  DEFAULT_INITIALIZE_VECTOR_SIZE: 16,
} as const;

export type CE_ENCRYPTIONER_DEFAULT =
  (typeof CE_ENCRYPTIONER_DEFAULT)[keyof typeof CE_ENCRYPTIONER_DEFAULT];
